language: python
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+(-(alpha|beta|rc)(\\.\\d+)?)?$/"
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
    env:
      - INTEGRATION_TEST=true
install: ".travis/install.sh"
script: ".travis/run.sh"
after_success:
- ".travis/upload_coverage.sh"
notifications:
  email: false
  slack:
    secure: dIcoapJPmlFSN/eHmGxklWy3TDvfACO0Ed5JhKbApYzbztvl9JB6ggmtpmq4NFWVkkJKnz7SaDTKdD7Qis7O+fOQ8hc2HMQ9BKC0dYiaBfJlxT68UsBbhhiUYARNNCXLAUSY81V/ea233EK4YyukYj/wKxi7W8uqfPh0/ZSQoCfNE9CW0IJdxIk73NDFshzxHJhPuIqnSvJuDbh9dfxIWUrezH0efe8CBROVHPxBehjCfLBrL/hNPZ6ryzZzqISYmStmQ31H/xmebdizqKEbtFb9AlYHh0yN+Lt2UFcXMI30e5AbDDkb+/gA1hN1hlQOvjpXl2ZiRrC+bwoeBX2dB0RqBz0UyNz6WWoD3w6ebebkVrZEgL6S9G+WdffOqvvElTE0nbR7HAQuzL+E1joqAR63XOhDQO5uT2BdGbJkpWqQQDkZJNBQAoBPLNsZ7oPr9WKvrfzJmkDOZRHEVzY/1FtubRjZAIrmY8xDACziI/XUVMNz2RtmfO9b4RQdP1u1KdFDRq5WbGLBi9B7vMUUVoVQVG6xrLDVG0Thi8DGF+cw/3VomqhERoIMb4WQf2zCVXKUfm5AFJ3VgikvOAV21/ACdDq/gw3RUVKLd3jUdvM2am3kGIxmTB7nq2wIkyLMoshOBcZlLyvRwkIvi+riVHN/XVArOc7wq6EwRS1Jkq0=
    on_success: change
    on_failure: always
before_deploy:
- pip install --upgrade twine setuptools
deploy:
  provider: pypi
  user: slarse
  password:
    secure: pMxkSyf2yvfm3jVdQp0YceZBQx6iqxDERS7oWtJisZtBItkv0LmCc5eUPLl2w9SnEpn7D+PZf5dKluYFvKmogp6cxzuvOJdv+cNtx/VoihCSncyEOHJQ59x83aOjkNcW+wD0SAUJ/hj7RuI2R+CJ6iUaVRnBQ20Em2wvMswZ/J4G6yDuzb91NCyroDIToDuseet/pGV2VnQt+TR8HxyNaEcuU6lqAXRJMhiJGuOYs/ok2iGo2yfBRfk0ENCP0jexVvY3aeMTMzoD7/1iWCxc7QThAlo6jbqLUovlVaxt0YqSpnhE860/7G/tOO0Py87HbcGg/BbddrGTOUA1YUBCNbwu3Den/GRHwMoxRtlwmdrXbmNpi6app1ESIhGPIR5nGtME4vq/ZErSYcI5tTqgO1wQ2fncyPGq8C460IH83sWUd8QjUIy9CU78suSaXEJFZkbXwOAr7IVqbWZmVkupEzJDKZMVA3c83KEQxXumwXOeAZ4LYTQHswGE89ib5iDyy2mxE9RDiC79dKskJC2CA5PyjFahlMM70N/TclXi7W0064DfX7tNkW+w/mAVonbkfBJMdnwqvGxP43n0V6MuUOkGKY3U9nBLMalt8AqnTcAaEblJNCc0FAliU7LJwedkN10pvlH6gKafYLIcS60FoNJDDPMkV/VgBNHBzYFKyoI=
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = "linux"
  distributions: sdist bdist_wheel
  repo: repobee/repobee
  skip_existing: true
