language: python
matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
  - os: osx
    language: generic
    sudo: true
    before_cache:
      - brew cleanup
    cache:
      directories:
        # cache homebrew
        - $HOME/Library/Caches/Homebrew
        - /Users/travis/.pyenv/versions
install: ".travis/install.sh"
script: ".travis/run.sh"
after_success:
- codecov
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Cq4Y2dwkNNE7hIZSEtmvNHI/2TZYzKpAJqbb6QPKG0hilx3PGetbs7fWy+ru6gRVW7A494Yk/4+ZO/9A92Pn0QHbbWtJZuU61pC2zxtkH2VKAzMVFly4gkL7L5Q9B8drAoer1usI4OtlN7eyqegTGAT8NEbhaynsJweEDZbWCWoXdQkl4tX6pYyDX/6HAWkfsQLaLPczLACyKYl812qAt7u6fFD+hcjdVrs/LfM9Cdt1gW3t9cVNm/Lqmla+I5OYjRRgbHm4XgsTrhNR0IoAxbktcxSwemnjTzwTsn7VQ9y4t8NlBRB5LUfw/0ihehKl7O4QS2c1G1uLhKHZZSfU8Di/qGGSvj/QBFvyZPDA8a/fmMBrNIHwy4k46l1ZfdDnX65oDbncHuXcFOVlTx85C5Zpy86tQDVktXf3kDlzsUtLgKtAY5dvLMDAwTvkX5M05DMwC51A+b2wsM1zs14CkeTFjHfsBIhDek91YfUEx6dRmnhg1KXVA+q02DKNoI0D5sNkOcgBnVATQOo29zcRKnyit93LBG3EiQYiIhubtwMkveXlEE3Qd5bUSdVuTMObN2nhm1bmYGrJ68dR+zKbsBZ51fcar6YeecmLCF6epBcZI++3AEH5/gu4qXb7A2pbxtiARJtxliI83d6CwEycPWhpjQ4p5UnByMhvKnKv14w=
before_deploy:
- pip install --upgrade twine setuptools
deploy:
  provider: pypi
  user: slarse
  password:
    secure: OTaXQPwYy0vvzsTOWd3xFI5MtfO9c2Y7PmIhuNaavcqElBnUbjkD2wikRGo/gz0vzpUpV41fQbvdQxXtvi7e5nYERSXogE2CY7+EcfT1IfCn9f9czl23g8sWQVIWd3Kz3uTUHqtYCraLIvbKNPZFSArulg86hYs8uZMtZ8c0CwY+0942rU+hUDIycQlZTP+ydjkKq1I/VpG33NSWz4dOgy7dfqNUyL56Uy0BUzcRRNMevNR/aFhJiYXXZW42qJEjXQDOytoxap9aHzV9LvNtqKa/sOB/bYnMyfzBtHHRc9MZFNfsQ68E5UFTriujL2G8Wu4+9RWYMKqkpqyVt1WVawT3ojatxH2xV9bKm3wDsT+wUMN4lYBlfygtEdk76jUHPHlEIA6JqiR8FsHupuB5FgHEVhg7KFg6icT7opDzx5xasvs0rydqguDcur6fvAMwin4/o5FNw2Nlx24wFtiQ0gxTkTLRmjgf8uL0UHZ4hruu3Dw666oxKlytWrw8wA6hmJUx96QmjWUHlcebck9KqNHRm0rYneU4ny2jZpMSVUvTP/UMK68xAG8vPLcpBnuLCDt1UYx161fu15mqruUnmoCLsGraGIWMGmNemAjE4f4RYAVtkv7VK4qSuYedwMmL8v/jOMop4Ky1Bg5dlES9COavEpqJFjN4ik1lFhtiV+4=
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_OS_NAME = "linux"
  distributions: sdist bdist_wheel
  repo: slarse/repomate
  skip_existing: true
