FROM python:3.7.4-stretch

COPY . /app
WORKDIR /workdir
RUN pip install --upgrade pip && pip install /app[TEST]
ENV REPOBEE_NO_VERIFY_SSL=true
ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# the integration test GitLab container has a self-signed certificate,
# so ssl verification in git must be turned off
RUN git config --global http.sslVerify false
RUN apt install bash
