# Workflow for deploying RepoBee to PyPi

name: deploy

on:
  push:

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Package RepoBee
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/app.txt -r requirements/test.txt
        python -m pip install .
        python setup.py sdist bdist_wheel
    - name: Publish RepoBee to PyPi
      run:
        ls dist
