# Workflow for deploying RepoBee to PyPi

name: deploy

on:
  release:
    types: published

jobs:
  deploy-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Package RepoBee
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/requirements.txt
        python -m pip install .
        python setup.py sdist bdist_wheel
    - name: Publish RepoBee to PyPi
      uses: pypa/gh-action-pypi-publish@29930c9cf57955dc1b98162d0d8bc3ec80d9e75c # v1.4.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
