
name: gitlab-system-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *"

  gitlab-system-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build RepoBee container
      run: docker build -t repobee:test -f Dockerfile.test .
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install RepoBee
      run: pip install -e .[TEST]
    - name: Run system tests
      run: |
        cd system_tests
        pytest test_gitlab_system.py -vv --showlocals
