# This workflow runs static analysis on RepoBee

name: static-analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/app.txt -r requirements/test.txt
        pip install -e .[TEST]
    - name: Lint with flake8
      run: flake8 . --statistics
    - name: Lint with Bandit
    - run: bandit -r src/ --skip B322 -ll
